### ISSUE TITLE
Roll-Out for TC Notes and Clarity

### ISSUE THREAD

**Issue by christianparker** [TrueCommerce/vscode-tctoolbox#12]
**Error on First Run if BETA/ALPHA**
If a user was previously using the original build for beta/alpha the will receive the error message:

C:/Users/[username]/.vscode/extensions/TrueCommerce.dotnet: Cannot read file ...

Deleting the directory resolves the issue.  However it's not intuitive that it is needed.  Please provide clarity in roll-out instructions on this.

**Clarity on Quiet Install**
Update user documentation to make it clear that when you install the toolbox in vsCode it will remain "Quiet" until done.  No notification of a successful install/start of install is given.

**Feedback (smiley face) Button**
Point out that the feedback/smiley face button (bottom right) is for MS only and not TCPSG Engineers.

**Comment by DotJoshJohnson** [comment]
These changes have been made in the quick start guide (http://toolbox.tcpsg.net). I'll leave the issue open to facilitate further improvements until the roll-out is complete.
